<a href="https://colab.research.google.com/github/SamudralaAnuhya/vectorization/blob/main/Vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import time

comparing the times between for loop and vector implmentation

In [3]:
a = np.random.rand(1000000 )
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("vectorized implementation:" + str(1000*(toc-tic)) + "ms" )

c=0
tic = time.time()
for i in range (1000000):
  c += a[i]*b[i]
toc = time.time()
print(c)
print("For loop implementation:" + str(1000*(toc-tic)) + "ms" )

249974.0328730776
vectorized implementation:1.3649463653564453ms
249974.03287307644
For loop implementation:581.5060138702393ms


Broadcasting

In [8]:
A = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])

In [9]:
cal = A.sum(axis = 0)
print(cal)

[15 18 21 24]


In [15]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[ 6.66666667 11.11111111 14.28571429 16.66666667]
 [33.33333333 33.33333333 33.33333333 33.33333333]
 [60.         55.55555556 52.38095238 50.        ]]


In [20]:
a= np.random.randn(10 , 1)
b = np.random.rand(1, 2)
print(a,b)

[[ 1.16342905]
 [ 0.00645427]
 [-0.526433  ]
 [-0.89928789]
 [ 1.01516892]
 [-0.70172376]
 [-1.98638494]
 [-0.24042908]
 [ 0.01802552]
 [-2.58690105]] [[0.9905157  0.62464977]]


In [6]:
a=np.random.randn(3,3)
b=np.random.randn(3,1)
c = a * b
print(c)

[[ 0.08589326 -0.57961489 -1.10759195]
 [-0.23319104 -0.24640737 -0.07718295]
 [-0.07797186 -0.13080228 -0.16224225]]
