<a href="https://colab.research.google.com/github/SamudralaAnuhya/vectorization/blob/main/Vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import time

comparing the times between for loop and vector implmentation

In [3]:
a = np.random.rand(1000000 )
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("vectorized implementation:" + str(1000*(toc-tic)) + "ms" )

c=0
tic = time.time()
for i in range (1000000):
  c += a[i]*b[i]
toc = time.time()
print(c)
print("For loop implementation:" + str(1000*(toc-tic)) + "ms" )

249974.0328730776
vectorized implementation:1.3649463653564453ms
249974.03287307644
For loop implementation:581.5060138702393ms


Broadcasting

In [8]:
A = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])

In [9]:
cal = A.sum(axis = 0)
print(cal)

[15 18 21 24]


In [15]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[ 6.66666667 11.11111111 14.28571429 16.66666667]
 [33.33333333 33.33333333 33.33333333 33.33333333]
 [60.         55.55555556 52.38095238 50.        ]]


In [20]:
a= np.random.randn(10 , 1)
b = np.random.rand(1, 2)
print(a,b)

[[ 1.16342905]
 [ 0.00645427]
 [-0.526433  ]
 [-0.89928789]
 [ 1.01516892]
 [-0.70172376]
 [-1.98638494]
 [-0.24042908]
 [ 0.01802552]
 [-2.58690105]] [[0.9905157  0.62464977]]


In [6]:
a=np.random.randn(3,3)
b=np.random.randn(3,1)
c = a * b
print(c)

[[ 0.08589326 -0.57961489 -1.10759195]
 [-0.23319104 -0.24640737 -0.07718295]
 [-0.07797186 -0.13080228 -0.16224225]]


In [8]:
#lineaer regression
import numpy as np

# Manually defining x (images) and y (labels)
X = np.array([
    [[82, 71, 68], [89, 83, 83], [100, 98, 104], [131, 132, 137], [126, 124, 124], [105, 97, 95]],
    [[95, 91, 97], [104, 104, 113], [110, 115, 126], [135, 134, 135], [127, 122, 119], [111, 105, 103]],
    [[94, 85, 83], [97, 89, 90], [110, 109, 115], [136, 134, 131], [127, 120, 117], [116, 108, 104]],
    [[96, 116, 131], [97, 115, 130], [103, 123, 139], [152, 155, 157], [146, 149, 152], [130, 133, 134]],
    [[90, 108, 123], [92, 108, 121], [100, 119, 134], [150, 152, 155], [144, 146, 147], [134, 135, 134]],
    [[86, 102, 116], [87, 103, 115], [94, 114, 127], [154, 156, 160], [146, 148, 152], [138, 141, 142]]
], dtype='uint8')

y = np.array([1, 1])  # Labels for these two images (both cats)


In [1]:
import numpy as np
import copy
import matplotlib.pyplot as plt
import h5py
import scipy
from PIL import Image
from scipy import ndimage
%matplotlib inline
%load_ext autoreload
%autoreload 2

Logistic Regression

In [9]:
#Th edata set for any the image will be seen like above for example [82, 71, 68]....red , blue, green and its like 3 set of values we need to make into 1 set

m = X.shape[1] #input values size
W = np.zeros(X.shape[0]) #1d array to add the values for the difference between predictionvalue and exact value
b = 0.0 #scalar value for small changes
#flatten
X_flatten = X.reshape(X.shape[0], -1).T    #FLatten dataset
#sigmoid (Activation function)
A = 1/(1+np.exp(-(np.dot(W.T , X) +b )))   #Sigmoid (logistic Regression using sigmoid function we need to find w,b). ... in finel I need to do this
#cost function
cost = -(1/m) * np.sum((Y * np.log(A))+ ((1-Y) * np.log(1-A))) #gradient descent loss function (Sum of loss is cost)
cost = np.squeeze(np.array(cost)) # remove dimensional array and make it as scalar

#we need to find w , b  .....w = w-alphs(dw)  ; b = b-alpha(db)
dw = (1 / m) * np.dot(X, (A - Y).T) #∂𝐽∂𝑤=1𝑚𝑋(𝐴−𝑌)𝑇(7)
db = (1/m) *np.sum(A-Y) #∂𝐽∂𝑏=1𝑚∑𝑖=1𝑚(𝑎(𝑖)−𝑦(𝑖))

#optimize
leanring_rate = 0.09
for i in range (100):   # here we should give number base on how many iterations should run for to reduce w,b values and give good prediction
  w = w - leanring_rate(dw)
  b = b - learning_rate(db)

#prediction
for i in range(A.shape[1]):
  if A[0,i] > 0.5:
    Y_prediction[0,i] =  1
  else :
    Y_prediction[0,i] = 0




