<a href="https://colab.research.google.com/github/SamudralaAnuhya/vectorization/blob/main/Vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import time

comparing the times between for loop and vector implmentation

In [3]:
a = np.random.rand(1000000 )
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("vectorized implementation:" + str(1000*(toc-tic)) + "ms" )

c=0
tic = time.time()
for i in range (1000000):
  c += a[i]*b[i]
toc = time.time()
print(c)
print("For loop implementation:" + str(1000*(toc-tic)) + "ms" )

249974.0328730776
vectorized implementation:1.3649463653564453ms
249974.03287307644
For loop implementation:581.5060138702393ms


Broadcasting

In [8]:
A = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])

In [9]:
cal = A.sum(axis = 0)
print(cal)

[15 18 21 24]


In [15]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[ 6.66666667 11.11111111 14.28571429 16.66666667]
 [33.33333333 33.33333333 33.33333333 33.33333333]
 [60.         55.55555556 52.38095238 50.        ]]


In [20]:
a= np.random.randn(10 , 1)
b = np.random.rand(1, 2)
print(a,b)

[[ 1.16342905]
 [ 0.00645427]
 [-0.526433  ]
 [-0.89928789]
 [ 1.01516892]
 [-0.70172376]
 [-1.98638494]
 [-0.24042908]
 [ 0.01802552]
 [-2.58690105]] [[0.9905157  0.62464977]]


In [6]:
a=np.random.randn(3,3)
b=np.random.randn(3,1)
c = a * b
print(c)

[[ 0.08589326 -0.57961489 -1.10759195]
 [-0.23319104 -0.24640737 -0.07718295]
 [-0.07797186 -0.13080228 -0.16224225]]


In [8]:
#lineaer regression
import numpy as np

# Manually defining x (images) and y (labels)
X = np.array([
    [[82, 71, 68], [89, 83, 83], [100, 98, 104], [131, 132, 137], [126, 124, 124], [105, 97, 95]],
    [[95, 91, 97], [104, 104, 113], [110, 115, 126], [135, 134, 135], [127, 122, 119], [111, 105, 103]],
    [[94, 85, 83], [97, 89, 90], [110, 109, 115], [136, 134, 131], [127, 120, 117], [116, 108, 104]],
    [[96, 116, 131], [97, 115, 130], [103, 123, 139], [152, 155, 157], [146, 149, 152], [130, 133, 134]],
    [[90, 108, 123], [92, 108, 121], [100, 119, 134], [150, 152, 155], [144, 146, 147], [134, 135, 134]],
    [[86, 102, 116], [87, 103, 115], [94, 114, 127], [154, 156, 160], [146, 148, 152], [138, 141, 142]]
], dtype='uint8')

y = np.array([1, 1])  # Labels for these two images (both cats)


In [1]:
def model(X, Y, learning_rate = 0.3, num_iterations = 30000, print_cost = True, lambd = 0, keep_prob = 1):
    """
    Implements a three-layer neural network: LINEAR->RELU->LINEAR->RELU->LINEAR->SIGMOID.

    Arguments:
    X -- input data, of shape (input size, number of examples)
    Y -- true "label" vector (1 for blue dot / 0 for red dot), of shape (output size, number of examples)
    learning_rate -- learning rate of the optimization
    num_iterations -- number of iterations of the optimization loop
    print_cost -- If True, print the cost every 10000 iterations
    lambd -- regularization hyperparameter, scalar
    keep_prob - probability of keeping a neuron active during drop-out, scalar.

    Returns:
    parameters -- parameters learned by the model. They can then be used to predict.
    """

    grads = {}
    costs = []                            # to keep track of the cost
    m = X.shape[1]                        # number of examples
    layers_dims = [X.shape[0], 20, 3, 1]

    # Initialize parameters dictionary.
    parameters = initialize_parameters(layers_dims)

    # Loop (gradient descent)

    for i in range(0, num_iterations):

        # Forward propagation: LINEAR -> RELU -> LINEAR -> RELU -> LINEAR -> SIGMOID.
        if keep_prob == 1:
            a3, cache = forward_propagation(X, parameters)
        elif keep_prob < 1:
            a3, cache = forward_propagation_with_dropout(X, parameters, keep_prob)

        # Cost function
        if lambd == 0:
            cost = compute_cost(a3, Y)
        else:
            cost = compute_cost_with_regularization(a3, Y, parameters, lambd)

        # Backward propagation.
        assert (lambd == 0 or keep_prob == 1)   # it is possible to use both L2 regularization and dropout,
                                                # but this assignment will only explore one at a time
        if lambd == 0 and keep_prob == 1:
            grads = backward_propagation(X, Y, cache)
        elif lambd != 0:
            grads = backward_propagation_with_regularization(X, Y, cache, lambd)
        elif keep_prob < 1:
            grads = backward_propagation_with_dropout(X, Y, cache, keep_prob)

        # Update parameters.
        parameters = update_parameters(parameters, grads, learning_rate)

        # Print the loss every 10000 iterations
        if print_cost and i % 10000 == 0:
            print("Cost after iteration {}: {}".format(i, cost))
        if print_cost and i % 1000 == 0:
            costs.append(cost)

    # plot the cost
    plt.plot(costs)
    plt.ylabel('cost')
    plt.xlabel('iterations (x1,000)')
    plt.title("Learning rate =" + str(learning_rate))
    plt.show()

    return parameters

Logistic Regression

In [9]:
#Th edata set for any the image will be seen like above for example [82, 71, 68]....red , blue, green and its like 3 set of values we need to make into 1 set

m = X.shape[1] #input values size
W = np.zeros(X.shape[0]) #1d array to add the values for the difference between predictionvalue and exact value
b = 0.0 #scalar value for small changes
#flatten
X_flatten = X.reshape(X.shape[0], -1).T    #FLatten dataset
#sigmoid (Activation function)
A = 1/(1+np.exp(-(np.dot(W.T , X) +b )))   #Sigmoid (logistic Regression using sigmoid function we need to find w,b). ... in finel I need to do this
#cost function
cost = -(1/m) * np.sum((Y * np.log(A))+ ((1-Y) * np.log(1-A))) #gradient descent loss function (Sum of loss is cost)
cost = np.squeeze(np.array(cost)) # remove dimensional array and make it as scalar

#we need to find w , b  .....w = w-alphs(dw)  ; b = b-alpha(db)
dw = (1 / m) * np.dot(X, (A - Y).T) #∂𝐽∂𝑤=1𝑚𝑋(𝐴−𝑌)𝑇(7)
db = (1/m) *np.sum(A-Y) #∂𝐽∂𝑏=1𝑚∑𝑖=1𝑚(𝑎(𝑖)−𝑦(𝑖))

#optimize
leanring_rate = 0.09
for i in range (100):   # here we should give number base on how many iterations should run for to reduce w,b values and give good prediction
  w = w - leanring_rate(dw)
  b = b - learning_rate(db)

#prediction
for i in range(A.shape[1]):
  if A[0,i] > 0.5:
    Y_prediction[0,i] =  1
  else :
    Y_prediction[0,i] = 0






initialization

In [ ]:
#deeplearning model
#Hyperparameter tuning ---Random initialization

#initialzing first w,b
# Zeros initialization -- setting initialization = "zeros" in the input argument.
# Random initialization -- setting initialization = "random" in the input argument. This initializes the weights to large random values.
# He initialization -- setting initialization = "he" in the input argument. This initializes the weights to random values  (relu)

#zero initialization (the cost doesn't decrease, and the algorithm performs no better than random guessing)
L = len(layers_dims) - 1
for l in range(1, L):
        parameters['W' + str(l)] = np.zeros((layers_dims[l], layers_dims[l-1]))
        parameters['b' + str(l)] = np.zeros((layers_dims[l], 1))
    return parameters

#initialize_parameters_random (multiply with 0.01 to  any but small makes better but how small it shoulb be ? here comes next he(relu))
 for l in range(1, L):
        parameters['W' + str(l)] = np.random.randn(layers_dims[l], layers_dims[l-1]) * 0.01
        parameters['b' + str(l)] = np.zeros((layers_dims[l], 1))
    return parameters


#He Initialization(Relu)sqrt(2/previous layer)(recommended method)
for l in range(1, L + 1):
        parameters['W' + str(l)] = np.random.randn(layers_dims[l] ,layers_dims[l-1])*np.sqrt(2/layers_dims[l-1])
        parameters['b' + str(l)] =np.zeros((layers_dims[l] ,1))
    return parameters


#Regularization ---adding lambda (lambd) in the cost function
two techniques - l2 regularization and dropout
$$J_{regularized} = \small \underbrace{-\frac{1}{m} \sum\limits_{i = 1}^{m} \large{(}\small y^{(i)}\log\left(a^{[L](i)}\right) + (1-y^{(i)})\log\left(1- a^{[L](i)}\right) \large{)} }_\text{cross-entropy cost} + \underbrace{\frac{1}{m} \frac{\lambda}{2} \sum\limits_l\sum\limits_k\sum\limits_j W_{k,j}^{[l]2} }_\text{L2 regularization cost} \tag{2}$$

#Dropout - decrease number of neurons in the layer


L2 regularization -- functions: "compute_cost_with_regularization()" and "backward_propagation_with_regularization()"
Dropout -- functions: "forward_propagation_with_dropout()" and "backward_propagation_with_dropout()"


In [ ]:
# What you should remember: the implications of L2-regularization on:

# The cost computation:
# A regularization term is added to the cost.
# The backpropagation function:
# There are extra terms in the gradients with respect to weight matrices.
# Weights end up smaller ("weight decay"):
# Weights are pushed to smaller values.


L2_regularization_cost = (lambd /  (2 * m))* (np.sum(np.square(W1)) + np.sum(np.square(W2)) + np.sum(np.square(W3)))


def backward_propagation_with_regularization(X, Y, cache, lambd):
    """
    Implements the backward propagation of our baseline model to which we added an L2 regularization.

    Arguments:
    X -- input dataset, of shape (input size, number of examples)
    Y -- "true" labels vector, of shape (output size, number of examples)
    cache -- cache output from forward_propagation()
    lambd -- regularization hyperparameter, scalar

    Returns:
    gradients -- A dictionary with the gradients with respect to each parameter, activation and pre-activation variables
    """

    m = X.shape[1]
    (Z1, A1, W1, b1, Z2, A2, W2, b2, Z3, A3, W3, b3) = cache

     # Compute gradients for the output layer
    dZ3 = A3 - Y
    dW3 = 1./m * np.dot(dZ3, A2.T) + (lambd / m) * W3
    db3 = 1. / m * np.sum(dZ3, axis=1, keepdims=True)

     # Propagate to the second layer
    dA2 = np.dot(W3.T, dZ3)
    dZ2 = np.multiply(dA2, np.int64(A2 > 0))
    dW2 = 1./m * np.dot(dZ2, A1.T) + (lambd / m) * W2
    db2 = 1. / m * np.sum(dZ2, axis=1, keepdims=True)


      # Propagate to the first layer
    dA1 = np.dot(W2.T, dZ2)
    dZ1 = np.multiply(dA1, np.int64(A1 > 0))
    dW1 = 1. / m * np.dot(dZ1, X.T) + (lambd / m) * W1
    db1 = 1. / m * np.sum(dZ1, axis=1, keepdims=True)

    gradients = {"dZ3": dZ3, "dW3": dW3, "db3": db3,"dA2": dA2,
                 "dZ2": dZ2, "dW2": dW2, "db2": db2, "dA1": dA1,
                 "dZ1": dZ1, "dW1": dW1, "db1": db1}

    return gradients

In [ ]:
#dropout...works based on keep_prob
# **What you should remember about dropout:**
# - Dropout is a regularization technique.
# - You only use dropout during training. Don't use dropout (randomly eliminate nodes) during test time.
# - Apply dropout both during forward and backward propagation.
# - During training time, divide each dropout layer by keep_prob to keep the same expected value for the activations. For example, if keep_prob is 0.5, then we will on average shut down half the nodes, so the output will be scaled by 0.5 since only the remaining half are contributing to the solution. Dividing by 0.5 is equivalent to multiplying by 2
#  Hence, the output now has the same expected value. You can check that this works even when keep_prob is other values than 0.5.

# 4 steps for each forward layer
# D1 = np.random.rand(A1.shape[0],A1.shape[1])  # Step 1: initialize matrix D1 = np.random.rand(..., ...)
#     D1 = (D1 < keep_prob).astype(int)             # Step 2: convert entries of D1 to 0 or 1 (using keep_prob as the threshold)
#     A1 =  A1 * D1                                 # Step 3: shut down some neurons of A1
#     A1 =  A1 / keep_prob

#for backward layer
    # dZ3 = A3 - Y
    # dW3 = 1./m * np.dot(dZ3, A2.T)
    # db3 = 1./m * np.sum(dZ3, axis=1, keepdims=True)
    # dA2 = np.dot(W3.T, dZ3)
    # dA2 = dA2 * D2                # Step 1: Apply mask D2 to shut down the same neurons as during the forward propagation
    # dA2 = dA2 / keep_prob

def forward_propagation_with_dropout(X, parameters, keep_prob = 0.5):
    """
    Implements the forward propagation: LINEAR -> RELU + DROPOUT -> LINEAR -> RELU + DROPOUT -> LINEAR -> SIGMOID.

    Arguments:
    X -- input dataset, of shape (2, number of examples)
    parameters -- python dictionary containing your parameters "W1", "b1", "W2", "b2", "W3", "b3":
                    W1 -- weight matrix of shape (20, 2)
                    b1 -- bias vector of shape (20, 1)
                    W2 -- weight matrix of shape (3, 20)
                    b2 -- bias vector of shape (3, 1)
                    W3 -- weight matrix of shape (1, 3)
                    b3 -- bias vector of shape (1, 1)
    keep_prob - probability of keeping a neuron active during drop-out, scalar

    Returns:
    A3 -- last activation value, output of the forward propagation, of shape (1,1)
    cache -- tuple, information stored for computing the backward propagation
    """

    np.random.seed(1)

    # retrieve parameters
    W1 = parameters["W1"]
    b1 = parameters["b1"]
    W2 = parameters["W2"]
    b2 = parameters["b2"]
    W3 = parameters["W3"]
    b3 = parameters["b3"]


    # Dropout for Layer 1
    # LINEAR -> RELU -> LINEAR -> RELU -> LINEAR -> SIGMOID
    Z1 = np.dot(W1, X) + b1
    A1 = relu(Z1)
    #(≈ 4 lines of code)         # Steps 1-4 below correspond to the Steps 1-4 described above.
    D1 = np.random.rand(A1.shape[0],A1.shape[1])  # Step 1: initialize matrix D1 = np.random.rand(..., ...)
    D1 = (D1 < keep_prob).astype(int)             # Step 2: convert entries of D1 to 0 or 1 (using keep_prob as the threshold)
    A1 =  A1 * D1                                 # Step 3: shut down some neurons of A1
    A1 =  A1 / keep_prob                          # Step 4: scale the value of neurons that haven't been shut down

    # Dropout for Layer 1
    Z2 = np.dot(W2, A1) + b2
    A2 = relu(Z2)
    #(≈ 4 lines of code)
    D2 = np.random.rand(A2.shape[0],A2.shape[1])  # Step 1: initialize matrix D2 = np.random.rand(..., ...)
    D2 = (D2 < keep_prob).astype(int)             # Step 2: convert entries of D2 to 0 or 1 (using keep_prob as the threshold)
    A2 =  A2 * D2                                 # Step 3: shut down some neurons of A2
    A2 =  A2 / keep_prob                          # Step 4: scale the value of neurons that haven't been shut down

    Z3 = np.dot(W3, A2) + b3
    A3 = sigmoid(Z3)

    cache = (Z1, D1, A1, W1, b1, Z2, D2, A2, W2, b2, Z3, A3, W3, b3)

    return A3, cache

# Gradient Checking
2 - Problem Statement

You are part of a team working to make mobile payments available globally, and are asked to build a deep learning model to detect fraud--whenever someone makes a payment, you want to see if the payment might be fraudulent, such as if the user's account has been taken over by a hacker.

You already know that backpropagation is quite challenging to implement, and sometimes has bugs. Because this is a mission-critical application, your company's CEO wants to be really certain that your implementation of backpropagation is correct. Your CEO says, "Give me proof that your backpropagation is actually working!" To give this reassurance, you are going to use "gradient checking."

Let's do it!

In [ ]:
# First compute "gradapprox" using the formula above (1) and a small value of $\varepsilon$. Here are the Steps to follow:
#     1. $\theta^{+} = \theta + \varepsilon$
#     2. $\theta^{-} = \theta - \varepsilon$
#     3. $J^{+} = J(\theta^{+})$
#     4. $J^{-} = J(\theta^{-})$
#     5. $gradapprox = \frac{J^{+} - J^{-}}{2  \varepsilon}$
# - Then compute the gradient using backward propagation, and store the result in a variable "grad"
# - Finally, compute the relative difference between "gradapprox" and the "grad" using the following formula:
# $$ difference = \frac {\mid\mid grad - gradapprox \mid\mid_2}{\mid\mid grad \mid\mid_2 + \mid\mid gradapprox \mid\mid_2} \tag{2}$$
# You will need 3 Steps to compute this formula:
#    - 1'. compute the numerator using np.linalg.norm(...)
#    - 2'. compute the denominator. You will need to call np.linalg.norm(...) twice.
#    - 3'. divide them.
# - If this difference is small (say less than $10^{-7}$), you can be quite confident that you have computed your gradient correctly. Otherwise, there may be a mistake in the gradient computation.


# GRADED FUNCTION: gradient_check_n

def gradient_check_n(parameters, gradients, X, Y, epsilon=1e-7, print_msg=False):
    """
    Checks if backward_propagation_n computes correctly the gradient of the cost output by forward_propagation_n

    Arguments:
    parameters -- python dictionary containing your parameters "W1", "b1", "W2", "b2", "W3", "b3"
    grad -- output of backward_propagation_n, contains gradients of the cost with respect to the parameters
    X -- input datapoint, of shape (input size, number of examples)
    Y -- true "label"
    epsilon -- tiny shift to the input to compute approximated gradient with formula(1)

    Returns:
    difference -- difference (2) between the approximated gradient and the backward propagation gradient
    """

    # Set-up variables
    parameters_values, _ = dictionary_to_vector(parameters)

    grad = gradients_to_vector(gradients)
    num_parameters = parameters_values.shape[0]
    J_plus = np.zeros((num_parameters, 1))
    J_minus = np.zeros((num_parameters, 1))
    gradapprox = np.zeros((num_parameters, 1))

    # Compute gradapprox
    for i in range(num_parameters):

        # Compute J_plus[i]. Inputs: "parameters_values, epsilon". Output = "J_plus[i]".
        # "_" is used because the function you have outputs two parameters but we only care about the first one
        #(approx. 3 lines)
        theta_plus = np.copy(parameters_values)                      # Step 1
        theta_plus[i] += epsilon                                    # Step 2
        J_plus[i], _ =   forward_propagation_n(X, Y, vector_to_dictionary(theta_plus))                                  # Step 3


        # Compute J_minus[i]. Inputs: "parameters_values, epsilon". Output = "J_minus[i]".
        #(approx. 3 lines)
        theta_minus = np.copy(parameters_values)                # Step 1
        theta_minus[i] -= epsilon                                 # Step 2
        J_minus[i], _ =   forward_propagation_n(X, Y, vector_to_dictionary(theta_minus))                              # Step 3


        # Compute gradapprox[i]
        # (approx. 1 line)
        gradapprox[i] = (J_plus[i] - J_minus[i]) / (2 * epsilon)

    # Compare gradapprox to backward propagation gradients by computing difference.
    # (approx. 3 line)
#     numerator = np.linalg.norm(grad - gradapprox)                    # Step 1'
#     denominator = np.linalg.norm(grad) + np.linalg.norm(gradapprox)  # Step 2'
#     difference = numerator / denominator
    numerator = np.linalg.norm(grad - gradapprox)           # Step 1': Compute the numerator (Euclidean norm of the difference)
    denominator = np.linalg.norm(grad) + np.linalg.norm(gradapprox)  # Step 2': Compute the denominator
    difference = numerator / denominator# Step 3'

    if print_msg:
        if difference > 2e-7:
            print ("\033[93m" + "There is a mistake in the backward propagation! difference = " + str(difference) + "\033[0m")
        else:
            print ("\033[92m" + "Your backward propagation works perfectly fine! difference = " + str(difference) + "\033[0m")

    return difference

Types of gradient descent
 1. Stochastic Gradient Descent .. it works each and evry value in the dataset and (online learning or ads)
 2. Mini-Batch Gradient Descent ...divide the data into batches and compute the gradient descent (gives good accuaracy and less time)
 epoch ...completing of all values in dataset in the batches is 1 epoche
 3. Batch Gradient Descent: (works on all elements on dataset and update gradient descent (slow and good accuracy)

In [ ]:
#Batch
X = data_input
Y = labels
m = X.shape[1]  # Number of training examples
parameters = initialize_parameters(layers_dims)
for i in range(0, num_iterations):
    # Forward propagation
    a, caches = forward_propagation(X, parameters)
    # Compute cost
    cost_total = compute_cost(a, Y)  # Cost for m training examples
    # Backward propagation
    grads = backward_propagation(a, caches, parameters)
    # Update parameters
    parameters = update_parameters(parameters, grads)
    # Compute average cost
    cost_avg = cost_total / m


# Stochastic Gradient Descent:
X = data_input
Y = labels
m = X.shape[1]  # Number of training examples
parameters = initialize_parameters(layers_dims)
for i in range(0, num_iterations):
    cost_total = 0
    for j in range(0, m):
        # Forward propagation
        a, caches = forward_propagation(X[:,j], parameters)
        # Compute cost
        cost_total += compute_cost(a, Y[:,j])  # Cost for one training example
        # Backward propagation
        grads = backward_propagation(a, caches, parameters)
        # Update parameters
        parameters = update_parameters(parameters, grads)
    # Compute average cost
    cost_avg = cost_total / m


#minibatch
def random_mini_batches(X, Y, mini_batch_size = 64, seed = 0):
    """
    Creates a list of random minibatches from (X, Y)

    Arguments:
    X -- input data, of shape (input size, number of examples)
    Y -- true "label" vector (1 for blue dot / 0 for red dot), of shape (1, number of examples)
    mini_batch_size -- size of the mini-batches, integer

    Returns:
    mini_batches -- list of synchronous (mini_batch_X, mini_batch_Y)
    """

    np.random.seed(seed)            # To make your "random" minibatches the same as ours
    m = X.shape[1]                  # number of training examples
    mini_batches = []

    # Step 1: Shuffle (X, Y)
    permutation = list(np.random.permutation(m))
    shuffled_X = X[:, permutation]
    shuffled_Y = Y[:, permutation].reshape((1, m))

    inc = mini_batch_size

    # Step 2 - Partition (shuffled_X, shuffled_Y).
    # Cases with a complete mini batch size only i.e each of 64 examples.
    num_complete_minibatches = math.floor(m / mini_batch_size) # number of mini batches of size mini_batch_size in your partitionning
    for k in range(0, num_complete_minibatches):
        # (approx. 2 lines)
        mini_batch_X =  shuffled_X[:, k * mini_batch_size:(k + 1) * mini_batch_size]
        mini_batch_Y =shuffled_Y[:, k * mini_batch_size:(k + 1) * mini_batch_size]
        mini_batch = (mini_batch_X, mini_batch_Y)
        mini_batches.append(mini_batch)

    # For handling the end case (last mini-batch < mini_batch_size i.e less than 64)
    if m % mini_batch_size != 0:
        #(approx. 2 lines)
        mini_batch_X = shuffled_X[:, num_complete_minibatches * mini_batch_size:]
        mini_batch_Y =shuffled_Y[:, num_complete_minibatches * mini_batch_size:]
        mini_batch = (mini_batch_X, mini_batch_Y)
        mini_batches.append(mini_batch)

    return mini_batches



**Optimization **   - The process of minimizing (or maximizing) a loss function to find the optimal model parameters J(w,b)

hyperparameters  = learning rate (alpha) , momentum (beta1 , beta2) , batchsize

**Momentum** - 	Accelerates gradient descent by adding a fraction of the previous gradient to the current update (V_DW , V_DB)

$$ \begin{cases}
v_{dW^{[l]}} = \beta v_{dW^{[l]}} + (1 - \beta) dW^{[l]} \\
W^{[l]} = W^{[l]} - \alpha v_{dW^{[l]}}
\end{cases}\tag{1}$$

$$\begin{cases}
v_{db^{[l]}} = \beta v_{db^{[l]}} + (1 - \beta) db^{[l]} \\
b^{[l]} = b^{[l]} - \alpha v_{db^{[l]}}
\end{cases}\tag{2}$$

**RMSProp **- Scales learning rate for each parameter based on the magnitude of recent gradients (S_DW , S_DB)

$$ \begin{cases}
s_{dW^{[l]}} = \beta s_{dW^{[l]}} + (1 - \beta) dW^{[l]**2} \\
W^{[l]} = W^{[l]} - \alpha S_{dW^{[l] }}
\end{cases}\tag{3}$$

$$\begin{cases}
S_{db^{[l]}} = \beta S_{db^{[l]}} + (1 - \beta) db^{[l]**2} \\
b^{[l]} = b^{[l]} - \alpha S_{db^{[l]}}
\end{cases}\tag{4}$$



**Adam **- Combines the advantages of Momentum and RMSProp to adapt learning rates for each parameter
$$\begin{cases}
v_{dW^{[l]}} = \beta_1 v_{dW^{[l]}} + (1 - \beta_1) \frac{\partial \mathcal{J} }{ \partial W^{[l]} } \\
v^{corrected}_{dW^{[l]}} = \frac{v_{dW^{[l]}}}{1 - (\beta_1)^t} \\
s_{dW^{[l]}} = \beta_2 s_{dW^{[l]}} + (1 - \beta_2) (\frac{\partial \mathcal{J} }{\partial W^{[l]} })^2 \\
s^{corrected}_{dW^{[l]}} = \frac{s_{dW^{[l]}}}{1 - (\beta_2)^t} \\
W^{[l]} = W^{[l]} - \alpha \frac{v^{corrected}_{dW^{[l]}}}{\sqrt{s^{corrected}_{dW^{[l]}}} + \varepsilon}
\end{cases}$$


In [ ]:
def update_parameters_with_adam(parameters, grads, v, s, t, learning_rate = 0.01,
                                beta1 = 0.9, beta2 = 0.999,  epsilon = 1e-8):
    """
    Update parameters using Adam

    Arguments:
    parameters -- python dictionary containing your parameters:
                    parameters['W' + str(l)] = Wl
                    parameters['b' + str(l)] = bl
    grads -- python dictionary containing your gradients for each parameters:
                    grads['dW' + str(l)] = dWl
                    grads['db' + str(l)] = dbl
    v -- Adam variable, moving average of the first gradient, python dictionary
    s -- Adam variable, moving average of the squared gradient, python dictionary
    t -- Adam variable, counts the number of taken steps
    learning_rate -- the learning rate, scalar.
    beta1 -- Exponential decay hyperparameter for the first moment estimates
    beta2 -- Exponential decay hyperparameter for the second moment estimates
    epsilon -- hyperparameter preventing division by zero in Adam updates

    Returns:
    parameters -- python dictionary containing your updated parameters
    v -- Adam variable, moving average of the first gradient, python dictionary
    s -- Adam variable, moving average of the squared gradient, python dictionary
    """

    L = len(parameters) // 2                 # number of layers in the neural networks
    v_corrected = {}                         # Initializing first moment estimate, python dictionary
    s_corrected = {}                         # Initializing second moment estimate, python dictionary

    # Perform Adam update on all parameters
    for l in range(1, L + 1):
        # Moving average of the gradients. Inputs: "v, grads, beta1". Output: "v".
        # (approx. 2 lines)
        v["dW" + str(l)] = beta1 * v["dW" + str(l)] + (1-beta1) * grads["dW" + str(l)]
        v["db" + str(l)] = beta1 * v["db" + str(l)] + (1-beta1) * grads["db" + str(l)]
        # Compute bias-corrected first moment estimate. Inputs: "v, beta1, t". Output: "v_corrected".
        # (approx. 2 lines)
        v_corrected["dW" + str(l)] = v["dW" + str(l)]/(1-beta1 ** t)
        v_corrected["db" + str(l)] = v["db" + str(l)]/(1-beta1 ** t)

        # Moving average of the squared gradients. Inputs: "s, grads, beta2". Output: "s".
        #(approx. 2 lines)
        s["dW" + str(l)] = beta2 * s["dW" + str(l)] + ((1-beta2) * (grads["dW" + str(l)]**2))
        s["db" + str(l)] = beta2 * s["db" + str(l)] + ((1-beta2) * (grads["db" + str(l)]**2))

        # Compute bias-corrected second raw moment estimate. Inputs: "s, beta2, t". Output: "s_corrected".
        # (approx. 2 lines)
        s_corrected["dW" + str(l)] = s["dW" + str(l)] / (1-beta2**t)
        s_corrected["db" + str(l)] = s["db" + str(l)] / (1-beta2**t)

        # Update parameters. Inputs: "parameters, learning_rate, v_corrected, s_corrected, epsilon". Output: "parameters".
        # (approx. 2 lines)
        parameters["W" + str(l)] -= learning_rate * v_corrected["dW" + str(l)] / (np.sqrt(s_corrected["dW" + str(l)]) + epsilon)
        parameters["b" + str(l)] -= learning_rate * v_corrected["db" + str(l)] / (np.sqrt(s_corrected["db" + str(l)]) + epsilon)

    return parameters, v, s, v_corrected, s_corrected